### ISSUE TITLE
Hourglass not displayed when loading big-ass file

### ISSUE THREAD

**Issue by pachuco** [katahiromz/RNotepad#1]
I threw an 83mb drwtsn32.log file into RNotepad for shits and giggles.
It displays text editor caret cursor while loading, which leaves me wonder if it's doing anything.

XP notepad instead displays waiting hourglass when mouseover Notepad window while loading.

**Comment by katahiromz** [comment]
Thank you for reporting that bug in your dirty words.

However, sorry, this is not `RNotepad`'s bug.
When running `RNotepad` on Windows 2003/XP, this bug couldn't reproduce.
In fact, hourglass cursor is displaying on Windows.

Therefore, I think it is ReactOS' bug.
Especially, it is related to the ReactOS ghosting window feature (not implemented yet).

**Comment by katahiromz** [comment]
Forwarded to https://jira.reactos.org/browse/CORE-11944 . Closed.

**Comment by pachuco** [comment]
> Thank you for reporting that bug in your dirty words.
> 
> However, sorry, this is not `RNotepad`'s bug. When running `RNotepad` on Windows 2003/XP, this bug couldn't reproduce. In fact, hourglass cursor is displaying on Windows.
> 
> Therefore, I think it is ReactOS' bug. Especially, it is related to the ReactOS ghosting window feature (not implemented yet).

Ah yeah, I forgot to say OS. My bad.

 I ran RNotepad on XP SP3 x86(Integral Edition; may contain traces of POSR2009 updates and nuts).

Did not try in ReactOS.

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5659

**Comment by katahiromz** [comment]
Hey, @pachuco. Can you try this one?
[notepad.zip](https://github.com/katahiromz/RNotepad/files/12544401/notepad.zip)

**Comment by pachuco** [comment]
Aye, that works as expected.

**Comment by katahiromz** [comment]
Fixed.
