### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Davilarek** [katahiromz/RNotepad#2]
Hello there, would it be possible to add dark mode? To save eyes :eyes:

**Comment by katahiromz** [comment]
How to detect dark mode
https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application

**Comment by katahiromz** [comment]
WM_CTLCOLOREDIT message
https://learn.microsoft.com/en-us/windows/win32/controls/wm-ctlcoloredit

**Comment by katahiromz** [comment]
Flat Scroll Bars
https://learn.microsoft.com/en-us/windows/win32/controls/flat-scroll-bars

**Comment by katahiromz** [comment]
https://gist.github.com/rounk-ctrl/b04e5622e30e0d62956870d5c22b7017

**Comment by katahiromz** [comment]
Support Dark and Light themes in Win32 apps
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes

**Comment by katahiromz** [comment]
https://github.com/HO-COOH/win32-darkmode

**Comment by katahiromz** [comment]
Hello, @Davilarek.

I don't support dark mode in this notepad. Sorry.
